name: sleep
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - ipywidgets
  - tifffile
  - nbformat
  - plotly
  - pip:
      - pymysql
      - ydata-profiling
      - h5py


